services:
  db:
    image: postgres:14.0
    name: pg_pokedex
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "8089:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
volumes:
  pgdata: