# Generated by Django 5.1.1 on 2024-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0007_alter_receita_imagereceita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imageReceita',
            field=models.ImageField(upload_to='receitaCovers/'),
        ),
    ]
