"""Adding unique constraint in Pokemon.name

Revision ID: 5246c020c7f3
Revises: ae7bd96d3535
Create Date: 2025-03-20 15:17:37.948737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5246c020c7f3'
down_revision: Union[str, None] = 'ae7bd96d3535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pokemon', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='unique')
    # ### end Alembic commands ###
