"""Adding unique constraints to other modelsc

Revision ID: 61f6a246ce04
Revises: 5246c020c7f3
Create Date: 2025-03-20 15:27:56.822931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f6a246ce04'
down_revision: Union[str, None] = '5246c020c7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ability', ['name'])
    op.create_unique_constraint(None, 'abilitycategory', ['name'])
    op.create_unique_constraint(None, 'abilitytype', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abilitytype', type_='unique')
    op.drop_constraint(None, 'abilitycategory', type_='unique')
    op.drop_constraint(None, 'ability', type_='unique')
    # ### end Alembic commands ###
