# Generated by Django 5.1.1 on 2024-10-31 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('categoryType', models.CharField(choices=[('BR', 'Café da manhã'), ('LU', 'Almoço'), ('SN', 'Lanche'), ('DI', 'Jantar'), ('AP', 'Apelitivo'), ('VE', 'Vegetariano'), ('VG', 'Vegano'), ('OT', 'Outros')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('idPage', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('titleReceita', models.CharField(max_length=150)),
                ('imageReceita', models.ImageField(upload_to='static/Receitas/imgs/%d/%m/%Y')),
                ('publicationDate', models.DateField(auto_now_add=True)),
                ('descriptionResumed', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=3000)),
                ('preparationTime', models.IntegerField()),
                ('preparationTimeUnit', models.CharField(choices=[('minutos', 'minutos'), ('horas', 'horas'), ('dias', 'dias'), ('meses', 'meses')], default='minutos', max_length=7)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Receitas.category')),
                ('userSubmitted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
