# Generated by Django 5.1.1 on 2024-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nameAdmin',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
