# Generated by Django 5.1.1 on 2024-10-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0003_rename_nameadmin_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
