# Generated by Django 5.1.1 on 2024-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0004_remove_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('1', 'Café da manhã'), ('2', 'Almoço'), ('3', 'Lanche'), ('4', 'Jantar'), ('101', 'Apelitivo'), ('102', 'Vegetariano'), ('103', 'Vegano'), ('50', 'Outros')], default='50', max_length=6),
        ),
    ]
