# Generated by Django 5.1.1 on 2024-11-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0005_alter_category_categorytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='descriptionResumed',
            new_name='Description Resumed',
        ),
    ]
