# Generated by Django 5.1.1 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0006_rename_descriptionresumed_receita_description_resumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imageReceita',
            field=models.ImageField(upload_to='static/Receitas/imgs/receitaCovers/'),
        ),
    ]
