# Generated by Django 5.1.1 on 2024-11-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0010_alter_category_categorytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Description Resumed',
            new_name='descriptionResumed',
        ),
    ]
