# Generated by Django 5.1.1 on 2024-11-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0011_rename_description_resumed_receita_descriptionresumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageCategory',
            field=models.ImageField(default='/category-covers/default.jpg', upload_to='category-covers/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('1', 'Café da manhã'), ('2', 'Almoço'), ('3', 'Lanche'), ('4', 'Jantar'), ('101', 'Apelitivo'), ('102', 'Vegetariano'), ('103', 'Vegano'), ('50', 'Outros')], default='50', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imageReceita',
            field=models.ImageField(upload_to='receita-covers/'),
        ),
    ]
