# Generated by Django 5.1.1 on 2025-01-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0012_category_imagecategory_receita_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preparationTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preparationTimeUnit',
            field=models.CharField(choices=[('minutos', 'minutos'), ('horas', 'horas'), ('dias', 'dias'), ('meses', 'meses')], default='minutos', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='userSubmitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('idStep', models.AutoField(primary_key=True, serialize=False)),
                ('stepNumber', models.IntegerField()),
                ('stepDescription', models.TextField(max_length=500)),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Receitas.receita')),
            ],
        ),
    ]
