# Generated by Django 5.1.1 on 2025-01-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0013_alter_receita_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
