# Generated by Django 5.1.6 on 2025-02-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0014_rename_steps_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='titleReceita',
            field=models.CharField(max_length=40),
        ),
    ]
